{% set name = "matchpy" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5788f5ad901e925ef90b9b4baa1fbe1f2c5822b9f631fd5de1ffb58ab4298231

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.7.0
    - pytest-runner
  run:
    - python >=3.6
    - multiset >=2.0,<3.0

test:
  imports:
    - matchpy

about:
  home: https://github.com/HPAC/matchpy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MatchPy is a pattern matching library for Python.

  doc_url: https://matchpy.readthedocs.io/
  dev_url: https://github.com/HPAC/matchpy

extra:
  recipe-maintainers:
    - asmeurer
    - hbarthels
    - Upabjojr
