{% set name = "matchpy" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a21d7a1e3de417b6d0b865c63958e09230e24bf104c31b754360a09bb7bcf5be

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.7.0
    - pytest-runner
  run:
    - python >=3.6
    - hopcroftkarp >=1.2,<2.0
    - multiset >=2.0,<3.0

test:
  imports:
    - matchpy

about:
  home: https://github.com/HPAC/matchpy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MatchPy is a pattern matching library for Python.

  doc_url: https://matchpy.readthedocs.io/
  dev_url: https://github.com/HPAC/matchpy

extra:
  recipe-maintainers:
    - asmeurer
    - henrik227
