travis:
  secure:
    BINSTAR_TOKEN: yuVvr7fXvb+avT6phOIX6+/3o1w3fUWkUonnTCE9GVgaBS4ep7+uX+3bA+d03b6rgxttxFK5LqI7tLf73aUmDpXEKqssxt5ekJvdl7PHkmwwKtaF09h9JBYLqke2MWBgcVSzvcbmEzMEi1txbb4QA66+PRPCTpAUh2AtBKbRc7WeZLzNsaqHDN71l50P1iMjxaKZM3ap0WxuGENiIRCmguSDzWsoK/ujoVVp/5IuLOSKTJ3BwDb7pVTWTcCYCgbtnxY1aYMGVQG61K2yqme8QPjUgOcHn37HfRl03jOU/SqtWVNIatpztMUkhZaMODCEKRkKCkJzxpRko5ShAM5voOoDwc0bQ7MWHmUmsysKyboTISeMFS2V/8PGsUqZ8R5tRG33sJeFJB5aZQ25+7b3CRpqSmEm6i4OSHC3hHnmrIoa8gnpAPcFBGpDoBiK2/tshY8RyOmeQp5ws9e6skkKCrmnPPEXY5sHPQa6cJdHo7JR7uv4SanMk5TWZ7gC3yppbDsvcut5Nq7sUbUKIE9yeDJQ6G4JTvPOG/CdK1aJ4Y5uR7veDlU8Xe6fhd4O90joCly73XeZC4PKd4y+e8zTcQ8zZCnm77SvJN+dLkMQZPjCLTxRgnt42xIu2Rdm5b8cb8G0fNfu/t3KSyjqHH/UarxKPr1fzB+wfpFk3vtKtlc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
